rendezvous_server = 'rustdesk.magendamd.com:21116'
nat_type = 1
serial = 0
unlock_pin = ''
trusted_devices = ''

[options]
key = '+Li02oekgNMPX9Aa6jPAJhJCE7Cuu6kmP1zB6nMpKMc='
relay-server = 'rustdesk.magendamd.com'
av1-test = 'Y'
custom-rendezvous-server = 'rustdesk.magendamd.com'